### ISSUE TITLE
Remember status of Neighbors checkbox

### ISSUE THREAD

**Issue by GMart** [liamcottle/meshtastic-map#15]
When refreshing the page, the neighbors checkbox is always cleared for me. Not sure if it's a browser issue.

Also, if I select a node then select view neighbors,  either "We heard" or "Heard us", then click the X to close that overlay, the neighbors are always unselected. The neighbors selection should go back to what was selected before.

**Comment by BillyBag2** [comment]
(@GMart There is a refresh button on the page that refreshes the data without changing the settings.)

**Comment by GMart** [comment]
Yes, I know about that. I'm saying that when clicking that refresh button, or refreshing the entire page, the neighbors checkbox is always unselected. It shouldn't be affected.

**Comment by liamcottle** [comment]
Yeah, I was "hiding" the main neighbours layer, when showing the node specific neighbours layer.

But by hiding the layer, it auto updates the settings. So now, if you show node specific neighbours, it just won't turn off the main neighbours layer anymore...

Fixed in 9ec07633d4219e73f483f751d3cb8ba093f21e1f
