### ISSUE TITLE
Remove waypoint

### ISSUE THREAD

**Issue by CamFlyerCH** [liamcottle/meshtastic-map#22]
Hello Liam and readers
I created a waypoint about 4 weeks ago. It is still visible on the (your) map. But in Android I could not set an expiration date. Since then I wiped the data of the Meshtastic app and now I am not able to edit or delete this waypoint anymore. (ID 4292587809) Also I think there is no persistence MQTT entry for that. So now it only exists in your database or am I wrong ? Any idea how I could edit or delete this waypoint now ?
I am grateful for tips.

**Comment by liamcottle** [comment]
Hey @CamFlyerCH,

I've deleted this waypoint manually from my map database.

As far as I know, the Android app doesn't support setting expiration for waypoints, and they all, by default, expire after 14 years or something...

You're right, if you nuke the app data, you won't be able to send the delete waypoint packet, which would automatically remove it from my map. Because of this, I have manually deleted it for you.

There's no way for you to do this on my map itself, and probably won't be a way to do this since it's going to be hard to prove you actually own the waypoints or the node that created them, as node ids are spoofable.

However, you could probably use the cli client (I haven't checked if this is possible), to send out a waypoint with the same id but with an expired timestamp. If it gets gated to MQTT, my map will pick that packet up, and update the database accordingly.
