### ISSUE TITLE
Feature Request - Add date stamp on gated messages

### ISSUE THREAD

**Issue by Paul-Pressure** [liamcottle/meshtastic-map#79]
Feature Request

We are using the gated message feature to check message arrival over Lora radio and its extremely useful. 

Please add, date-stamp to each message. 

Love your work is a fantastic map and features

**Comment by SubnetConflict** [comment]
^ ^ One up on this one please - Especially when monitoring several nodes

**Comment by liamcottle** [comment]
Howdy! Thanks for the feedback :)

I've updated the messages UI to show the full date time instead of the relative time ago when you click on a message in the list.

Hope this helps!

<img width="388" alt="Screenshot 2024-11-07 at 11 15 03 PM" src="https://github.com/user-attachments/assets/ff133c8d-4e49-4a12-92fc-605b28422901">

**Comment by Paul-Pressure** [comment]
Hi Liam

Thank you.  to explain what we are using your gated messages for see  https://pole1.co.uk/trial/
this is extremely useful data so our local mesh can see who receives a message sent via mesh/lora

I was hoping for each individual message to have a time-stamp so we can see when it received via your MQTT.

Hope that makes sense 🙂

Cheers
Paul
________________________________
